### ISSUE TITLE
[Question] How to query the relationship values from GraphQL?

### ISSUE THREAD

**Issue by BrunoQuaresma** [datocms/plugins#31] opened 2021-05-20 13:41 UTC
Hi folks, just a simple question, how to query the relationship values from GraphQL?

**Comment by stefanoverna** [comment] 2021-05-21 07:35
Duplicate of https://community.datocms.com/t/graphql-query-for-json-fields/1921/2

**Closed by stefanoverna** 2021-05-21 07:35 UTC
