### ISSUE TITLE
plugin not responding

### ISSUE THREAD

**Issue by danidev** [datocms/plugins#61] opened 2022-07-22 08:00 UTC
Hello,

I get this message from the dato plugin settings after the update:

The plugin at https://unpkg.com/datocms-plugin-conditional-fields@0.1.1/build/index.html is not responding correctly after 20 seconds.

Can you please check?

Thank-you,
Daniele

**Comment by marcelofinamorvieira** [comment] 2022-07-26 11:44
Hello @danidev,

I couldn't reproduce the error, adding the plugin through https://www.datocms.com/marketplace/plugins/i/datocms-plugin-conditional-fields seems to work as expected.
We recently did an update on the addition of plugins through the marketplace that may have incidentally solved this issue, could you check if you can add it normally now?

**Comment by stefanoverna** [comment] 2022-08-23 08:22
It was probably a temporary downtime to unpkg.com. Closing for now!

**Closed by stefanoverna** 2022-08-23 08:23 UTC
