### ISSUE TITLE
Implement nested conditionals in Conditional fields

### ISSUE THREAD

**Issue by thimovss** [datocms/plugins#4] opened 2019-03-26 14:40 UTC
A ( conditional plugin )
-B ( conditional plugin )
--C 
When you have a field (C) which is nested inside a conditional field (B), that is inside another conditional field (A) then C will sometimes show if B is on, and A is off.

**Comment by gmjonker** [comment] 2019-06-18 10:39
+1

**Comment by matjack1** [comment] 2019-07-01 10:07
Hey @thimovss and @gmjonker sorry for the long delay in getting back to you.

What do you mean by "nested"? You can have one conditional showing/hiding one field and then another conditional showing/hiding another field. But the first one is not linked with the third in any way.

So if you show the third and then you hide the second the third will remain visible.

If that's your issue I don't think we can do much about it as I think it's outside the scope of this plugin. Or let me know if I haven't fully understood your issue.

Thank you!

**Comment by thimovss** [comment] 2019-07-15 08:36
It has been a while and it is not relevant for me anymore, but let me try to recall what the case was.
Think of it almost as like a directory structure.
For example, you have 3 fields, A B and C.
A is the conditional for B and C. And B is the conditional for C.
In this scenario you want C only to show if both A and B are true.
But what happens, is that C shows depending on which conditional, A or B, loads last. Which can cause C to show, whilst A is false.
@matjack1

**Comment by matjack1** [comment] 2019-07-23 12:27
@thimovss the problem is that we don't support this nested usage, so if you have A that controls both B and C when you show/hide that it will override any other setting enforced by B.

I'll rephrase the issue and mark it as an enhancement, thank you for your time explaining this!

**Comment by matjack1** [comment] 2019-10-14 13:25
I'm closing this feature request and move it here: https://community.datocms.com/t/nested-conditionals-in-conditional-fields-plugin/449

so that we can have a unique place for prioritizing feature requests.

Thank you for opening this!

**Closed by matjack1** 2019-10-14 13:25 UTC
Labels: enhancement
